---
- name: Demonstrate find module in Ansible
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Task to use find module
      find:
        paths:
          - /etc
          - /var
          - /usr
        patterns:
          - '*.old'
          - '*.log.gz'
          - 'passwd'
          - 'httpd'
        recurse: yes
      register: out

    - name: Print all matched file paths
      debug:
        msg: "{{ item.path }}"
      loop: "{{ out.files }}"
