---
- name: Create a user and add ssh public key to user's authorized keys
  hosts: localhost
  become: true
  remote_user: jenkins
  tasks:
   - name: Add a user
     user:
       name: ashishoness
       password: "{{ 'test123' | password_hash('sha512')}}"
       state: present
   - name: Task to add SSH keys to the user
     authorized_key:
      user: ashishoness
      state: present
      key: "{{lookup('file', '/home/jenkins/.ssh/id_rsa.pub')}}"
...
